### ISSUE TITLE
20201119 회의

### ISSUE THREAD

**Issue by HyeseonLee** [HyeseonLee/hotel-db-system#25]
회의 내용 : 발표 시나리오 시연 중심으로 작성

**PBL2 발표 시나리오**
- 3-4분 : 6조의 개발 방법(tool(framework, databbase), 업무 분담, 역할분담 how)
6조의 개발 point

- 5-6분 시연 : 각 입장별로 시나리오 구성 (시나리오 단위로 시연 끊어서 보여주기)

<고객 시나리오>

- [x] 1. [고객] 고객 A가 호텔을 예약하려고 회원가입을 한다. _(정우)_
- [x] 2. [고객] 예약을 한다. _(지윤)_ --> 예약 가능한 객실 보이기 (O) 예약 데이터 제출은 (아직)
- [x] 3. [고객] 예약 날짜가 되어서 고객이 호텔을 방문했다. 체크인을 하였다. 
- [x] -> 프론트 직원이 실시간 예약 상황 페이지를 틀어서, 체크인 상태로 바꾸어준다. (체크인 시간 기록)
- [x] 4. [고객] 출출한 A는 (~~~를 주문한다.) → 결제는?? “checkout 할 때 됩니다.” 
(RoomService 모델에 주문 data를 담아서 넘긴다) _(혜선)_

 
<업무별 시나리오>
(근태)
- [x] 5. 출근을 한 B는 직원 dash보드에 로그인을 하여 -> 근태를 입력한다. (오늘 일을 나왔는지 확인하는 필드 필요! 직원 출근 상태 확인 (draw.io에는 없다)) _(정우)_ --> 근태 내역은 보여진다(log로)

(식음료팀)
- [x] 6. [직원] 식음료 부서 B에게 업무 요청이 할당 된다. 직원은 dashboard에서 업무 할당된 것을 확인하고 On Progress로 옮기고 업무를 시작한다. _(승현)_
- [x] 7. [직원] B가 업무를 시작하고, Done으로 옮기면 -> 자동으로 Robot에게 일이 배정된다. -> 로봇이 A에게 음식을 전해준다. _(승현)_

(고객의 전화 예약으로 업무)
- [x] 8. [직원] 고객에게 전화를 받아 실시간 예약을 한다. 
: 실시간 예약 상황 페이지에서 날짜 룸타입 고객에게 듣고, 예약이 되어 있지 않은 룸을 클릭한다 -> 예약 info를 적는 창이 뜨고(미리 input태그 채워 두기 for 시간절약) -> 예약이 반영되어 룸의 색깔이 바뀌게 하기 _(지윤)_

(기술지원)

[경영진]

- [x] 9. 경영진 칸반보드에 근태 관리하는 줄을 하나 만든다. (dummy data 필요) 반차 승인을 합니다 !! _(정우)_ -->휴가 신청을 보여주는것 (O) , 승인해서 DB변경은 (아직)

**Comment by HyeseonLee** [comment]
혜선(PadApp)
: RoomService 주문 리스트를 담은 RoomServiceCart 모델 만들기(menu, price)
: 메뉴 디테일한 사진 보여지는 page url 추가

**Comment by glossyyoon** [comment]
RoomApp model에 checkin, checkout날짜, reserved status 추가, 
booking_room_id에 null true로 변경, 
직원이 실시간 예약상황을 볼 수 있는 template만들기

실시간 예약 상황 페이지에서 날짜 룸타입 고객에게 듣고, 예약이 되어 있지 않은 룸을 클릭한다 -> 예약 info를 적는 창이 뜨고(미리 input태그 채워 두기 for 시간절약) -> 예약이 반영되어 룸의 색깔이 바뀌게 하기

**Comment by lolmc00** [comment]
## 임승현(TaskApp)
- 요청을 할당할 때 출근한 직원(Attendance 테이블)만 필터링해서 할당해야함
- 룸서비스 만들고 완료하면 바로 로봇에게 할당되도록 변경

**Comment by right-x2** [comment]
고객이 회원가입을 하는 경우 예약페이지로 이동하게 하기

UserApp 모델에 경영진 모델 추가하기, staff에 근태관리 관련 필드 추가하기
직원 로그인 시 근태관리 페이지로 이동하게 하기
근태관리 template 추가하기

UserApp model dummy data 추가하기
