### ISSUE TITLE
frontend app별 html 파일 개요

### ISSUE THREAD

**Issue by HyeseonLee** [HyeseonLee/hotel-db-system#6]
<기본 구조>

앱
└ static
    └ css
    └ js
    └ image
└ templates
    └ ~~.html

**Comment by HyeseonLee** [comment]
앱
└ static
    └ css
    └ js
    └ image
└ templates
    └ ~~.html

**Comment by right-x2** [comment]
login.html - 고객 로그인 화면
signup.html - 고객 회원가입화면
staff_login.html- 직원 로그인화면
mypage.html- 직원 마이페이지 화면

**Comment by hikhjin** [comment]
로그인(직원번호 입력) - login.html
메인페이지(칸반보드) - main.html
실시간 예약 상황 - reservation.html
업무 분배 - task.html

**Comment by glossyyoon** [comment]
reserve_main.html : 날짜 입력받는 메인 페이지
reserve.html: 예약내역 확인 페이지
reserve_list.html: 남은 객실 확인 페이지
reserve_bill.html: 계산 페이지

**Comment by lolmc00** [comment]
request_assign.html: 중앙에서 기타요청 직원에게 할당하는 페이지
